### ISSUE TITLE
travel_speed cannot be fractional

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#10]
Since travel_speed is in km/h it seems fair to allow values such as 3.5 km/h, which is a perfectly normal walking speed. One could round to 3 or 4, but the difference is significant at such small values.

**Comment by labiblm** [comment]
@YuriGrings, this needs a sure update.

**Comment by YuriGrings** [comment]
Should be fixed now
