### ISSUE TITLE
10% hardcoded

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#11]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/availability.py#L124

This should probably be configurable in a production package.

**Comment by YuriGrings** [comment]
Personally, I don't think that it is relevant for users to make this configurable. It solely serves as an additional margin to the already user-specified buffer zone.
