### ISSUE TITLE
date range misses the last day of december

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#12]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/availability.py#L139

should be ...-12-31, or possibly entirely configurable if part-year coverage is desired

**Comment by YuriGrings** [comment]
Fixed range to 31-12 for now
