### ISSUE TITLE
configurable output files

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#14]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/availability.py#L182-L185

This could be a default, but it would be nice if output filenames were configurable.

**Comment by labiblm** [comment]
Agreed, and also change the save file to .tif not .png

**Comment by YuriGrings** [comment]
Save file changed to .tif

**Comment by YuriGrings** [comment]
All output files should now be configurable
