### ISSUE TITLE
Strange to return strings "true" / "false" instead of bool values

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#15]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/accessibility.py#L311-L313

**Comment by YuriGrings** [comment]
Changed to boolean values
