### ISSUE TITLE
buffer_dist does not have units of measure

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#16]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/Documentation/get_viewshed_GVI.md?plain=1#L23

assuming 'metres' but should be documented

**Comment by YuriGrings** [comment]
Added
