### ISSUE TITLE
Error claims that observer_height must be an int

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#17]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/visibility.py#L106

The code works with floats too but the error message is wrong.

Also, this is another example of #8 where it is unclear why TypeError is used & perhaps should be an application-specific error.

**Comment by YuriGrings** [comment]
Error message fixed
