### ISSUE TITLE
Also check if access_token is valid looking

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#19]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/visibility.py#L340

It would be best if you check if the access_token looks like a mapillary token (they all begin with 'MLY', I believe). This is because your own example code supplies an optional argument `access_token="MAPILLARY_API_TOKEN"` and if the user forgets to change the default then they just get a very mysterious error message further down the chain. It may not be obvious if they don't look closely that they have to supply a valid access token when running the example. It would be very easy to check that a valid-looking token was supplied, at least.

**Comment by YuriGrings** [comment]
Check added to verify whether or not token starts with "MLY"
