### ISSUE TITLE
typo: 'euclidian' instead of 'euclidean'

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#2]
This appears in several places, but here is one:

https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/Documentation/get_mean_NDVI.md?plain=1#L17

**Comment by YuriGrings** [comment]
Fixed
