### ISSUE TITLE
What is f?

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#20]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/visibility.py#L519

This function could use a better name.

**Comment by YuriGrings** [comment]
Fixed

**Comment by YuriGrings** [comment]
Fixed
