### ISSUE TITLE
get_GVI computation issue

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#21]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/visibility.py#L864-L871

Note that the way ‘get_GVI’ is written it computes the average percentage of several segments, rather than computing the percentage of vegetation pixels over all segments. If all segments have the same number of pixels then these two concepts are equivalent. However, if some segments are smaller and some segments are larger, then there is a difference. The way that `get_GVI` is written it would over-emphasise the importance of small segments and under-emphasise the importance of large segments. Think about an extreme (and silly) example with two segments: one segment has 2 pixels, of which none are green, and the other has 1000 pixels, of which 900 are green. The average percentage would be 45%. But I think it would be reasonable to argue that the correct percentage should be close to 90% (approx. (900 + 0) / (1000 + 2)) since the 2-pixel segment carries little information about the image.

Anyway it would be good to be sure about which way is intended.

Would it be more sensible simply to compute GVI on the whole panoramic image (corrected for distortion) rather than cutting segments out?

**Comment by labiblm** [comment]
@iabrilvzqz, please share the update for what you fixed in your section.

**Comment by YuriGrings** [comment]
Updates provided by Ilse are now integrated
