### ISSUE TITLE
personal pathnames in docs

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#22]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/README.md?plain=1#L41

Please don't put personal pathnames into documentation (here & in some other places too). Either reference a checked-out git repo, or show how to download the files from the internet.

**Comment by YuriGrings** [comment]
Removed from readme, I believe they are now only included in the notebooks that are used for development
