### ISSUE TITLE
redundant lines of code

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#3]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/availability.py#L52C3-L55

these are a duplicate of the following 3 lines

**Comment by YuriGrings** [comment]
Fixed
