### ISSUE TITLE
MULTIPOLYGON support

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#4]
The GM_polygon1.gpkg test file contains a MULTIPOLYGON which seems to cause functions to fail if they were expecting a POLYGON - is this intended?

**Comment by YuriGrings** [comment]
From my side, this was intended due to the function objectives. I'm currently not sure if and how multipolygon objects may affect the interpretability of the outcomes.

**Comment by labiblm** [comment]
I think we should give the multi polygon as an input file as there will be cases where they have multiple parts in the same polygon. This update will not change the interpretability!

**Comment by YuriGrings** [comment]
MultiPolygon geometries should now be supported
