### ISSUE TITLE
Option to provide POI data directly instead of a filename to read it from

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#6]
For the relevant functions: seems like it would be useful if I could load the POI file myself and then provide it to these functions, already in memory. Especially if the POI data is not actually from a file and computed dynamically. It’s handy to have the functions read it from the file for you, but if I provide it as a geopandas dataframe it should just use it & skip reading it from the file. Should be a 1-line fix.

**Comment by labiblm** [comment]
Matt, can you be a bit specific about which POIs are you indicating and which lines of code?

**Comment by YuriGrings** [comment]
Users should now also be able to provide POIs directly
