### ISSUE TITLE
ValueError vs TypeError

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#8]
It’s not clear why one is used over the other, e.g. availability.py lines 54, 59 and 69 all seem to be checking the same sort of thing but have different error types. Maybe make your own error type to express more specifically what you mean? This applies across all your code.

**Comment by labiblm** [comment]
@YuriGrings, can you please see if this can be updated?

**Comment by YuriGrings** [comment]
Error types are updated, only using ValueError and TypeError
