### ISSUE TITLE
Confusing undocumented interacting logic for polygon_type and buffer_type

### ISSUE THREAD

**Issue by mrd** [Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py#9]
https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/availability.py#L63

https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/GreenEx_Py/blob/f24db15a3d650712d653414ea3b8aa04a7a33126/GreenExp/availability.py#L68

Regarding the above two lines of code:

There seems to be a connection between the logic here that may not be intended. If polygon_type is ‘house’ then the geom_type will become ‘Point’ but if the buffer_type is left as default then the error will be raised at Line 69. The docs are not clear on this, and in fact suggest that buffer_type is optional: ‘optional in case point_of_interest_file contains polygon geometries’ but this is not true if polygon_type is ‘house’. Confirmed this is triggered if you provide POLYGONs and do not set buffer_type.

**Comment by YuriGrings** [comment]
Info added to docs, does this make it a bit more clear?
